---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-credentials
  namespace: pgadmin
spec:
  encryptedData:
    email: AgCvNXdSxNJgHBaAnasDJxfMzF4HD3sVzWBwlBgYGtyp2HKukxCHbzolcXkNnJq01nYCuCdyOPNtuZv2aeP2Ah+gZMuh+0BOM2JaOBJbogBNUPm6cbXnIwJxTSWRcLKJSUZI1Ofxw93w2xPFZsT12t6CzX/KbM3Cu6R4rBXSzVNEj10zF39/2k05UEmQEaUOiRsSb+efBsOI29+ImbKqCYSqFsVfq8ang8axb6UHawRLZDiFbbzB7OTJfcZvcRFwa5ULann/Zl2Lj8pur7/Wb7yk9J0nQJ6Jc3ot+fIEWd2iTlK3MlPUyQ+3Y/tn0ZKPYMrQ5JEs+330k/+L9AK1G6RmKJFoJKV/ZLvz0CngzIOes0oagQm25o/5iTKv9EoCjhZ3SogKUdCsthM39MEd5bQN8Ovuy7HQBy4Mih+kzMdLWXfwj5fsr+GxUtIgdRaTZtpmtAMuWGwHoUFmcFYAQnb9wP+UryLRJIu1WROQRBjf93sy3t1cLYU3CCItiyUAY4cYROkj8ASEAsMNAkL0FCwc2angkWOzxEvtJ9iRHcr/XL6R7r4+ZxM8Cc/a56QcQrZHOSXyVRKJuh7lcKN8PBzZSX/AXiTmdBdO7twc46ZQW8j6Xn8ehaa/r8893YCT43IM8xCn4h5LVODgebQA8HcnPonzL8BSzsQ5fZRBU7pUWvQ+TtIGcsTzfaYxYii7/wq9WWCzD21pBNnAflEMG3MEZtrd8w==
    password: AgBksOa2VRdV8Le9bxogdmxKqPlxRGreuB6J32ez2Vkxhjsz0MVtyr6ImTzmpanprICD+llR3br9CxQTQx/NMdyRs5zSTFxrDIBmT+OQ5cZpUlXNz+gWAdF5ZTp3w56r0HpfnHYbyI0JQoo0jK9+2qd0A/terILn/WTReT1WQSMThnmwYnrOtucboCblX0xn0Ly4gaJ1GcrZdr9d+yHXNkZ1Bu4rQ+FZAkNZEaeQ4d7YuDEL/KRGMzmNRBllCktdNUgCn1LcJxvwE1G8hSwIHIcI/rMU5lq9yM3fkeZUqtuTSwg8Q22M9jblCvqq7T8IUtSeDgZSR1JCO3FKABMMIf1pdgBRt7Bvc7y12UIBdHSdSJ1D2qiF0VB3BBENbtKe/mcjs/v1vwL7iHCNwV6VHEgj3Ql9riUDwKN2QqSXBR1YTosYwuP0tbJKf176/ZWY+BxrEI9egrxvgDwIrgPV5UbZu08FdIF3mnMoI5ranPawKxhS1ugwVojU+lFOMMFQWD7JUIHHCfZ5l6HPly8EK4kRN9b3t9w6ApT0EoExnNglw8lDW1HGPmRFKLa7hxrG+7sGc2mGsRssAHh6HC6frH6djcjAkHFrhHZ2/mcBtV4nH6E75e5Hp/DyQl5eCx65OQ+6w1iGEIzawvvhIovzqXm7lwZ0Z7iccssKU3cVyfBO3tkrx7Tr3XRtxZR4jZPGktOoHNE5mpfe6ipRhyW2ndP2
  template:
    metadata:
      name: pgadmin-credentials
      namespace: pgadmin
