apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 0103537e-f2f2-47a7-be22-1c5d3c93c661
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: portfolio.samirmahmoud.net
        service: http://traefik.kube-system.svc.cluster.local:80
      - service: http_status:404