apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
  namespace: cloudflared
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared-container
          image: cloudflare/cloudflared:2026.9.3
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts:
            - name: config-volume
              mountPath: /etc/cloudflared/config
            - name: creds-volume
              mountPath: /etc/cloudflared/creds
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: config-volume
          configMap:
            name: cloudflared-config
        - name: creds-volume
          secret:
            secretName: tunnel-credentials
