---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBwU8irmmtGUot02wZFElX8At97H59ZvMmpJQdYb7AJmeHLx0rEVmgNBWMnxfTILjWePwkdaLWmGi+Bta0WJG0X13/2qVNMJuABFVvFVWX/rpx7N18+HJNfj93Ydf518rTlYA4N1m3HY5PsWoyb0erHBfQqoYskIKVWBGd/G7XDDa9+9TIofWbbBKQzphekaV5LLZkUbwtpcIkNE5tRo9c5/UU68b/SSHRVFHy3GH/xkBSKpxt6iXnD97TMirLvixhR8y0mwa56wFibsuRAyDMEcBJZ3f+4wyZnms8hupVf+6/mGla0n8Snfyys3OyejFQhAoQ4v4aOhBswTitqMzkJ+yidtZMKp/Imre6ZIagtJZYTCxfb9tB9KA9ojMB3FxVXKOdb5wbgSF4w32p/wZpU6z32L2N6mtCcVHhtL9wIi9W+pgf5H61zF3D+rg5vT4brCWXfFSJ9/ngshKvlR/KGDJiV5W3nKyCPlzafa8X8T2dS9gIBHql6PtKfJ+Q0YGnNEg/pZiwtC9+FDXm1GmFWwQL5445vDuNwQ/TTu3kEgeVSH0StHQPD91UQxn0olwD5rgNp1JrT7JCkIf9VY16leyy9AH1E42TmXvwpuceAi78pfn/Bk2t8wndIJajtdDx679rWshqa5tAa9oezzUI2T3Pui32rcAmnAzCIRrH8HmRvs8CBYRlbjjskAlQeGKAgC2Aoj8TuyAiDbD6dgQMxvxY3wdFWRWqG5QuZiVsW6VP8S/z5F2nZw/lU98jHCu1LT7O8w7rbQRk3B52EKH8j1pwBgnRJ0rz0rAFIJRCTQ3BkIueoGehEsrrWnfnuP58TRGzBYbpksVD5i0XGsjsxbkMFGfsHqa8j7sNKTu4GYl7y3/oFs7gc1rxtGpo1AcDBlcanxgsGUbNsTKPXw5c/pmhJXY7mOqtiG6gxWzZX
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
