apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared-service-monitor
  namespace: cloudflared
  labels:
    app: cloudflared-service-monitor
    release: monitoring
spec:
  selector:
    matchLabels:
      app: cloudflared-service
  endpoints:
    - port: metrics-port
      path: /metrics
      interval: 30s