---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-r2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgB9L8xiUcll4qO0WifA9pbJ7ESpb80B9n24e9wQBLnm480vOfW6+78LNJP53G0BHwbNGiGxQR3WDVUKiUjWBJadVWwaxxkz2d0ATt3FBwKJlnGkEvLhkRrYq38cwM9M3VtaRotWcDq1f+FVRhNiXZndbEHn4qKFMyhUnO9b8SThpJPk/q7VUh9LrPxcfj5qvPPv/lNzInZWkMTJRh4pRF7z1tblfKk/jAdFXfk7GR5HpQ0lelUbl5RWQ8PwaNAGFP72YSaUYSXqzi1UuDnYngCTVA08HAsD11SO3DTJayOtx28DwX+feNEvn/unI4a3+njHFKglhXw0azZJITbwh0Dx4UUifIIukk2jJRvB88Srd8G3axcBec1bZDxC/Q6fw91uUBuaV6rF62WfNykccsAXwaS5kzLwmFStaaIa1WXfJAsWA5+zI2ZaiV0HDbCq/OvuP4z8K9IRhP8YFvUKpb06+Kvr0yzgDZIc2IQ40fwIryBtkapIHqSKNA61L8MvAiYtPKpYQUXue7aW7eJe1mGZrXmrZYaNShcfswF2HovPDpiaUIxvE+QZbUEmY6vNcQVgPZ+58ka0gJgo0RCD92DPz1yyzHbr9J9dbRmhHqIw8XjW7JDszM9SYLVLwFEC8Lcz8SdCeh2YM5r2dOv8XkS0CkbWCtKsONoqMmYo22OdvefnuqeeU5s4pkMbfQ3kxh2bKHYduPTLXKeyXqGDYgBVzqMiJwteJtVahFZnp4f7Va9lou61t/RilqN4htSmJAs6REnfkwomdrW6ST4TV5Hyy1k9pZjng41nB7Iyh/eaNdH2j+jNljJP1UDJEJYCD8MaFGdc4tjPPumXGlHTxmj2BHu6kGUQwuq7GX2/rNdC6RZyRmPebKihU//WRvluSiRTz1Wd
  template:
    metadata:
      name: velero-r2-credentials
      namespace: velero
