---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB6Oomsk+HKJbVUqAQU/9rdo2FP2OfgbXGXyvZ4aui0ybY/6p9Iq2vKMmWrYopSBZrp9mCbbQPynzQUyHMTe3kaTBilOCPXW9YdvySgf6t9UXmsc0ryz0RNqV406mq4JysIodWlIB9IfLvHZE97eEoFCqngIc+Rx47x54+U4SbYL6h0MlRr4zd4RZBYVDAMPzlc89R7h5WaSlTm0jrgpg+V/y6deSOwhCwQ9ExdnyEhwu8WWtrVdVhDJrBYeX+JHQO5GqUIu1trrpONjKNze2gdgvV+ObAc+DlTX8sm1gdW2EwUtHywAs/bkSw20HF6bsUrNHLdlpyrahjpKhheVWvay0ylkeB+4VhfgLXzWgYApkmgY9XvgokMuMAna++ZQ61AzzGS330ehm/RzjimhOsmZpBcbEAJUd9xbkalNtvLMhKuIj0TeNR/T+tqfcH99yF1ie7kXJL++zXIBmX56DN7wgOiqzr5c1AxR4n4hfbM9vTXKh66hTtV5htu7wLDL/AUTJv5iqLbx6g0rIiTdVNJgTT92Kmvc3E68354wOGDu/harkrgssyLGzhKChltu9HaB6lviby9j7swTQOjuygsnLtEa5oFjCr3HGPH/mRH6kn6pukCLG8QwYF0Nr4mQ+Q5f2TTk8zMrp/Ndj6TEO759sWy2tbUy5v2sbl9GB+p2OzHzbyIPjiME2qvCESoP8UxAxf3UEkN6tywWxE=
    admin-user: AgBjZIdVyidutsTgPnz4NBBDs8yl29OrQMheqfbgjETSmZ8JUnR3crfwWbTErxnyh3zFfK0hgTlIeCij94UZUUq3RbX4xSliHP+atPesJ5mcR3FwxvHSGnlrYa5T0PXA5EA8/PqiHoZhpqAKY8TzalqQ3mU3tImBrYLuel4cLispNJhgdVikpLX1cyBb5xcVYYVtUz5xNncZRc/dXlWVVAUdzrivFDzsxrvwI6jz1kxQccjLM1TAtG5LShaPNqmG/2MSa4VEGdQ6qR45j3hgVXNpUqKLfwEi7PtTSCMJJhqQdT8EBtoBXoT9YoyqwEBTHuNYFp8enjqcuqdrbGibCGjxNpcWaRQ3LHexV8H105zWjNrubbS1s0mzAMfVROt+sjMwyjiMl2i+Mf4l7wGeu7cJpcmxLKIA595IytAMW4+/K9iKqwr015WIRP+zCiLZ4mIJsKzoHYOfjmbmCHE8CQgmu+uQyvUE+KsPoZc6+ZEuGjfVxgA43UtKWd/2TFsb2yvyN/9+vV8BkpWkJA9omzSEF3/UfvadFyn0ME0rLLW/+8QRoemNk3Vb4WlKnK2tVpa49beruUKeG5ob6Z7BNypiHh4lWzsOct6LsGXj+agnMmwDXLZZC5XZmVWwcPNppSQGa1ylM6Q/noWu21Rm6z/QJyBeswZm8lsgtovdUdViSwgBBtoewobA8y7OE3yRxlXKt53oJA==
  template:
    metadata:
      name: grafana-credentials
      namespace: monitoring
