---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgBFWFp5ilQIBjnWxDdonEVLDZKr4Lj9Euzu849SqFCNf/1qdIqTygBu1HZDnrGECsvkKESayDOgH1NwKMkYo+/7aPTIovJfOpKvwreEaCbOFqtQCuIPGyLQOPyB2Ra0T0hKScMcoFgrUCdRIbyTtGXC5mKLFeQdTsgByMWtfUkhHi7O5Q0iiDVV/tDcNXKwtqvThBhn68xWe+Jb3a/XjtmpZy1UOVfc/4ipcuXkV4ASDgrKPyaVyUQSnsdj4ATRPAge4FpbaBu7EaFo+Hnf3/QK9kkxNZfWErVODQfU6jEjM+pz2ReJDALinMeQsiuXlny0hSzpAp8tnU7nQ671FYZOuv/fk5RxCrJrPBelOxauRUZ0VNDmlZIr9di+E2gYM5e5/L8optf58iu8Oqr9ONBFNcyuA+jH6uX57A9n3S2Hha3uNgXj8WNCozQ6QkbESLCopZ3yYJbRlT7vAx4bx4sr4jx9FkXWi61begurRNs78wIbgyIT8Px2gqVuGPK3KzDIpkbvUaGf5bEPH3ivqFVEu914OrKD/YjZuv4dbne7TRh1k3xVJasUmnYa5aWPjJn48Sx/mUORFHt3LSnFqrO4MsXYS8Af87tatMegZRo+q2MK1VCOh+qt7PX9ao11BVYWAk8wmIZMTBHlRnahYSW/XkqlYvvd8VpnrbDiXKszdBAkJ+5jgrVRQdBiSIhLSFuU5pHCkeb7Tys7KU1xad6c+P76xl9qiSm1EeAuWRcaQVRKJieCAonSB/p1ZE6+f9Ly/wwrCICZRR1USn+/Hp05QHYyDzLCIeg5OTFg4Uw/OoE=
  template:
    metadata:
      name: alertmanager-slack
      namespace: monitoring
