apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-pvc
  namespace: zurg
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
