apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr-deployment
  namespace: zurg
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        workload-strength: ram-heavy
      containers:
        - name: prowlarr-container
          image: ghcr.io/hotio/prowlarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9696
          startupProbe:
            httpGet: { path: /ping, port: 9696 }
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet: { path: /ping, port: 9696 }
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet: { path: /ping, port: 9696 }
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-pvc
        #   hostPath:
        #     path: /volume1/k3s/media/prowlarr/config
        #     type: DirectoryOrCreate
