apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: abyss-spotlight
    namespace: zurg
    files:
      - spotlight/spotlight.html
      - spotlight/spotlight.css
      - spotlight/spotlight-loader.js
