---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-credentials
  namespace: jenkins
spec:
  encryptedData:
    jenkins-admin-password: AgBozUBgGUXhp2zZvSFHEBVbfj4uoXN6rmNc1KA3fhQfadVFsDR7pykHNVMFyj9rt4iBD9t7+Pj5Aba+49iGGd0Zcijyh5hmJop7H0Y4C+PMS6Ut8/U2GjwnD8jLeGeF+h5dEqq9MmJn1m3WOmVeamVxO82PLWg0yG48bv7nv9KZkZ0Kh3jjpFXf3S8e/iPI3ZtUH8WYPyD+4ehzg+mKv8wgr7nopTGnMZGtLnhfd2Yw4z1xNyS0IyJybRKEQyNFo25yCDRVlrXeAUnzT69LuCtI+MCX4+OLNAZ32EsusR5uE/YP8g0Atpmt7BwhjF5mKPswvFU857XcfpMplnLH4htpyIZZcNYOVCcAM0ClNu02PxXxqPjUDmbeCnuCVzY6vf8h3DhjjWZe0mPxBVJiAll9wSb8tWlKSDMDGU5W2Ug6sjfVHgJprezNot/n2ZgGWXSJ8qXxGLM4ldTY7u1LtBkB5dFKa27tkhISREXucxhP5gpJSFothlmdT27QeTSImEWCj949I8EfZNdItz9rbNCI0cd7FpGUtYG9Lx7C5STyDZikpo1iM9KrvON64kFBZ4dJLwSVq5RjLEERfQKiI/64+MSm5G+EzLy7dkY7VCW0FSWgAEH04cxPw5Lc01Z8i10ylfcXjMGZUwH3wR4CEHI2/474YJ+6dDVF7XfJRrmUy+xC/zCNc3JzjUibBJKaiNn7KaWXwCQm7gJ9s7TUqmiaTC57fHW+
    jenkins-admin-user: AgAmtIsluf56oPFvd0X0fqkgiIQWtz7LX+6Rc3FX6p7DeW7I1fgnyUAGH+X6sguVY5GksPDslUbwnNEyk92dXojx7zSSCY3LwRIL5ktxCjzqZbP7WFUzlW3BRActYAR4WS6ym/+yMcTM0sgSTgbkxqzRt87T2Z+804+7F6mVYVy+12QK4QknhHGd60N9AQ5i+jAIPDpa5EbUkCI43MM0gHYLDfYB/mqvXtrqP0Gtn691QSuETa1VnQols+HmkGVaR6iDKyEtBw7b4i6sL0jATxF5J57pL1145s+Grg9Hk9tkutpK4r4sDQ7cSMUCSWt6Ge72MyckFTH+tllw2WJX8E5P7HqXM5EFaUE4twz7SzfWItGiBRUw+L1fqFvK0UqoUZF56C+jqULQL0WC+ITuc8T8mTdwvBGWjE4cxD/rvepEmoiw2owN0oliZ0jxP2CvyD3IsuL/HVT5zaITUHT3H3jr/lEZE1iUsR7bGbr/j5BVvGZ9c9iOjsjUvZNsTA/aWxwCUpHglbDBDGiXt3NVqX4amIHLHsZCnsEbdNIlamQgE26aK2JMRJtC/zooRyx6eC2bLpLu8D1weeJLQEdPLrDhHvXxJrEC2v0+z+UVv2HElLL34XdWqDsjBH6g2UmGLIXVRAfIx8jmTdYrRdUuEFrXYop/297Fz1noLBm6OVFNEgwWoRl044d2VtTLfv69pTHfhTYoRg==
  template:
    metadata:
      name: jenkins-credentials
      namespace: jenkins
