apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 91.9.0
    helm:
      valuesObject:

      # Prometheus configuration
        prometheus:
          ingress:
            enabled: true
            ingressClassName: "traefik"
            hosts:
              - prometheus.100.119.68.88.nip.io
          prometheusSpec:
            podMetadata:
              annotations:
                backup.velero.io/backup-volumes: prometheus-monitoring-kube-prometheus-prometheus-db
            nodeSelector:
              workload-strength: "cpu-heavy"
            retention: 15d
            retentionSize: 18GiB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
      # Grafana configuration
        grafana:
          podAnnotations:
            backup.velero.io/backup-volumes: storage
          ingress:
            enabled: true
            ingressClassName: "traefik"
            hosts:
              - grafana.100.119.68.88.nip.io
          admin:
            existingSecret: "grafana-credentials"
            userKey: "admin-user"
            passwordKey: "admin-password"
          persistence:
            enabled: true
            size: 5Gi
          deploymentStrategy:
            type: Recreate
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeProxy:
          enabled: false
        # Alert manager configuration
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: "traefik"
            hosts:
              - alertmanager.100.119.68.88.nip.io
          alertmanagerSpec:
            podMetadata:
              annotations:
                backup.velero.io/backup-volumes: alertmanager-monitoring-kube-prometheus-alertmanager-db
            secrets: ["alertmanager-slack"]
            storage:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 1Gi
          config:
            route:
              receiver: "slack-samir"
            receivers:
              - name: 'null'
              - name: "slack-samir"
                slack_configs:
                  - api_url_file: /etc/alertmanager/secrets/alertmanager-slack/webhook-url
                    send_resolved: true
          

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
      automated:
          prune: true
          selfHeal: true
      syncOptions:
          - ServerSideApply=true