apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secrets
  namespace: argocd
spec:
    source: 
        repoURL: git@github.com:SaMoBTW/homelab-config.git
        path: manifests/monitoring
        targetRevision: HEAD
    destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
    project: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true