apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
    source: 
        repoURL: git@github.com:SaMoBTW/homelab-config.git
        path: manifests/platform
        targetRevision: HEAD
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    project: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
