apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
    source: 
        repoURL: git@github.com:SaMoBTW/homelab-config.git
        path: manifests/prowlarr
        targetRevision: HEAD
    destination:
        server: https://kubernetes.default.svc
        namespace: zurg
    project: default
    # manual sync until first adoption verified; then add automated prune+selfHeal
