apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 12.2.0
    helm:
      valuesObject:

        schedules:
          daily:
            schedule: "0 7 * * *"
            useOwnerReferencesInBackup: false
            template:
              ttl: "336h"
              includedNamespaces:
                - monitoring
                - jenkins
                - pgadmin
              excludedResources:
                - secrets
        metrics:
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: monitoring
          prometheusRule:
            enabled: true
            additionalLabels:
              release: monitoring
            spec:
              - alert: VeleroBackupFailed
                annotations:
                  message: Velero backup {{ $labels.schedule }} failed
                expr: velero_backup_last_status{schedule!=""} != 1
                for: 15m
                labels:
                  severity: warning
              - alert: VeleroNoRecentBackup
                annotations:
                  message: No successful Velero backup for {{ $labels.schedule }} in 25h
                expr: (time() - velero_backup_last_successful_timestamp{schedule!=""}) > 25 * 3600
                for: 15m
                labels:
                  severity: critical
        initContainers:
            - name: velero-plugin-for-aws
              image: velero/velero-plugin-for-aws:v1.14.4
              volumeMounts:
                - mountPath: /target
                  name: plugins
        credentials:
          useSecret: true
          existingSecret: velero-r2-credentials
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: homelab-velero
              default: true
              config:
                region: auto
                s3ForcePathStyle: "true"
                s3Url: https://35e8f4fb6c09ea8e3686c41727b95531.r2.cloudflarestorage.com
        snapshotsEnabled: false
        deployNodeAgent: true

  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
      automated:
          prune: true
          selfHeal: true
      syncOptions:
          - ServerSideApply=true